FROM debian:trixie-slim

RUN apt-get update && \
    apt-get -y upgrade --no-install-recommends && \
    apt-get -y install --no-install-recommends \
        dirmngr \
        apt-transport-https \
        ca-certificates \
        gpg \
        gpg-agent

RUN gpg --keyserver keyserver.ubuntu.com --recv-key '95C0FAF38DB3CCAD0C080A7BDC78B2DDEABC47B7' && \
    gpg --armor --export '95C0FAF38DB3CCAD0C080A7BDC78B2DDEABC47B7' | gpg --dearmor | tee /usr/share/keyrings/cran.gpg > /dev/null && \
    echo "deb [signed-by=/usr/share/keyrings/cran.gpg] https://cloud.r-project.org/bin/linux/debian bookworm-cran40/" | tee /etc/apt/sources.list.d/cran.list && \
    apt-get -y install \
        libssl-dev \
        libxml2-dev \
        libcurl4-openssl-dev \
        libfontconfig1-dev \
        libharfbuzz-dev \
        libfribidi-dev \
        libfreetype6-dev \
        libpng-dev \
        libtiff5-dev \
        libjpeg-dev \
        r-base && \
    apt-get clea

COPY Install_packages.R install_packages.R
    
RUN R -e "install.packages('devtools', dependencies=TRUE)" && \
    Rscript install_packages.R