FROM debian:bookworm-slim

RUN apt-get update && \
    apt-get -y upgrade --no-install-recommends && \
    apt-get -y install --no-install-recommends \
        dirmngr=2.2.40-1.1 \
        apt-transport-https=2.6.1 \
        ca-certificates=20230311 \
        software-properties-common \
        gpg-agent=2.2.40-1.1 && \
    gpg --keyserver keyserver.ubuntu.com --recv-key '95C0FAF38DB3CCAD0C080A7BDC78B2DDEABC47B7' && \
    gpg --armor --export '95C0FAF38DB3CCAD0C080A7BDC78B2DDEABC47B7' | gpg --dearmor | tee /usr/share/keyrings/cran.gpg > /dev/null && \
    echo "deb [signed-by=/usr/share/keyrings/cran.gpg] https://cloud.r-project.org/bin/linux/debian bookworm-cran40/" | tee /etc/apt/sources.list.d/cran.list && \
    apt-get -y install \
        libssl-dev=3.0.15-1~deb12u1 \
        libxml2-dev=2.9.14+dfsg-1.3~deb12u1 \
        libcurl4-openssl-dev=7.88.1-10+deb12u8 \
        libfontconfig1-dev=2.14.1-4 \
        libharfbuzz-dev=6.0.0+dfsg-3 \
        libfribidi-dev=1.0.8-2.1 \
        libfreetype6-dev=2.12.1+dfsg-5+deb12u3 \
        libpng-dev=1.6.39-2 \
        libtiff5-dev \
        libjpeg-dev=1:2.1.5-2 \
        r-base=4.2.2.20221110-2 \
        r-base-dev=4.2.2.20221110-2 && \
    apt-get clean && \

COPY install_packages.R install_packages.R
    
RUN R -e "install.packages('devtools', dependencies=TRUE)" && \
    Rscript install_packages.R